/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArbitrageRouteImport } from './routes/arbitrage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminFounderContactRouteImport } from './routes/admin/founder-contact'
import { Route as AdminEarlyAccessRouteImport } from './routes/admin/early-access'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitrageRoute = ArbitrageRouteImport.update({
  id: '/arbitrage',
  path: '/arbitrage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFounderContactRoute = AdminFounderContactRouteImport.update({
  id: '/admin/founder-contact',
  path: '/admin/founder-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEarlyAccessRoute = AdminEarlyAccessRouteImport.update({
  id: '/admin/early-access',
  path: '/admin/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/founder-contact': typeof AdminFounderContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/founder-contact': typeof AdminFounderContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/founder-contact': typeof AdminFounderContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arbitrage'
    | '/dashboard'
    | '/login'
    | '/admin/dashboard'
    | '/admin/early-access'
    | '/admin/founder-contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arbitrage'
    | '/dashboard'
    | '/login'
    | '/admin/dashboard'
    | '/admin/early-access'
    | '/admin/founder-contact'
  id:
    | '__root__'
    | '/'
    | '/arbitrage'
    | '/dashboard'
    | '/login'
    | '/admin/dashboard'
    | '/admin/early-access'
    | '/admin/founder-contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArbitrageRoute: typeof ArbitrageRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEarlyAccessRoute: typeof AdminEarlyAccessRoute
  AdminFounderContactRoute: typeof AdminFounderContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitrage': {
      id: '/arbitrage'
      path: '/arbitrage'
      fullPath: '/arbitrage'
      preLoaderRoute: typeof ArbitrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/founder-contact': {
      id: '/admin/founder-contact'
      path: '/admin/founder-contact'
      fullPath: '/admin/founder-contact'
      preLoaderRoute: typeof AdminFounderContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/early-access': {
      id: '/admin/early-access'
      path: '/admin/early-access'
      fullPath: '/admin/early-access'
      preLoaderRoute: typeof AdminEarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArbitrageRoute: ArbitrageRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEarlyAccessRoute: AdminEarlyAccessRoute,
  AdminFounderContactRoute: AdminFounderContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
